forum/urls.py
from django.urls import path

from . import views

app_name = "forum"
urlpatterns = [
    # # ex: /polls/
    # path("", views.index, name="index"),
    # # ex: /polls/5/
    # path("<int:topic_id>/", views.detail, name="detail"),
    # # ex: /polls/5/commentsection/
    # path("<int:topic_id>/commentsection/", views.commentsection, name="commentsection"),
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/commentsection/", views.CommentSection.as_view(), name="commentsection"),
    # ex: /polls/5/comment/
    path("<int:topic_id>/likecomment/", views.likecomment, name="likecomment"),
]

welcome/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("forum/", include("forum.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

forum/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Topic(models.Model):
    topic_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.topic_text
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)
    def __str__(self):
        return self.comment_text

forum/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.db.models import F
from django.urls import reverse
from django.views import generic
from .models import Topic, Comment


# def index(request):
#     latest_topic_list = Topic.objects.order_by("-pub_date")[:5]
#     context = {
#         "latest_topic_list": latest_topic_list,
#     }
#     return render(request, "forum/index.html", context)


# def detail(request, topic_id):
#     topic = get_object_or_404(Topic, pk=topic_id)
#     return render(request, "forum/detail.html", {"topic": topic})


# def commentsection(request, topic_id):
#     topic = get_object_or_404(Topic, pk=topic_id)
#     return render(request, "forum/commentsection.html", {"topic": topic})

class IndexView(generic.ListView):
    template_name = "forum/index.html"
    context_object_name = "latest_topic_list"

    def get_queryset(self):
        """Return the last five published topics."""
        return Topic.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Topic
    template_name = "forum/detail.html"


class CommentSection(generic.DetailView):
    model = Topic
    template_name = "forum/commentsection.html"


def likecomment(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    try:
        selected_comment = topic.comment_set.get(pk=request.POST["comment"])
    except (KeyError, Comment.DoesNotExist):
        # Redisplay the topic voting form.
        return render(
            request,
            "forum/detail.html",
            {
                "topic": topic,
                "error_message": "You didn't select a comment.",
            },
        )
    else:
        selected_comment.likes = F("likes") + 1
        selected_comment.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("forum:commentsection", args=(topic.id,)))

forum/templates/forum/commentsection.html
<h1>{{ topic.topic_text }}</h1>

<ul>
{% for comment in topic.comment_set.all %}
    <li>{{ comment.comment_text }} -- {{ comment.likes }} like{{ comment.likes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'forum:detail' topic.id %}">Like again?</a>

forum/templates/forum/detail.html
<form action="{% url 'forum:likecomment' topic.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ topic.topic_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for comment in topic.comment_set.all %}
        <input type="radio" name="comment" id="comment{{ forloop.counter }}" value="{{ comment.id }}">
        <label for="comment{{ forloop.counter }}">{{ comment.comment_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Like">
</form>

forum/templates/forum/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'forum/style.css' %}">

{% if latest_topic_list %}
    <ul>
    {% for topic in latest_topic_list %}
        <li><a href="{% url 'forum:detail' topic.id %}">{{ topic.topic_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No forum are available.</p>
{% endif %}